dgpu: fix UI issues; Args: switch to GUC=2

diff --git a/apps/t2-dgpu-control/contrib/t2-dgpu-control-helper b/apps/t2-dgpu-control/contrib/t2-dgpu-control-helper
--- a/apps/t2-dgpu-control/contrib/t2-dgpu-control-helper
+++ b/apps/t2-dgpu-control/contrib/t2-dgpu-control-helper
@@ -74,12 +74,13 @@ apply_configuration() {
 
 	case "$profile" in
 		power-saving)
+			[[ "$power" != power-off ]] ||
+				fail "the AMDGPU power-saving profile requires the discrete GPU to remain powered"
 			systemctl enable "$POWER_PROFILE_SERVICE" "$POWER_PROFILE_RESUME_SERVICE"
 			set_power_profile power-saving
 			;;
 		default-profile)
 			systemctl disable "$POWER_PROFILE_SERVICE" "$POWER_PROFILE_RESUME_SERVICE"
-			set_power_profile default
 			;;
 		*)
 			fail "invalid AMDGPU power profile"
@@ -111,18 +112,11 @@ set_power_profile() {
 			fail "AMDGPU power-profile controls are unavailable on ${dev##*/}"
 		found=1
 
-		case "$mode" in
-			power-saving)
-				grep -Eq '^[[:space:]]*2[[:space:]]+POWER_SAVING' "$dev/pp_power_profile_mode" ||
-					fail "AMDGPU device ${dev##*/} does not expose POWER_SAVING as profile 2"
-				printf 'manual\n' >"$dev/power_dpm_force_performance_level"
-				printf '2\n' >"$dev/pp_power_profile_mode"
-				;;
-			default)
-				printf '0\n' >"$dev/pp_power_profile_mode"
-				printf 'auto\n' >"$dev/power_dpm_force_performance_level"
-				;;
-		esac
+		[[ "$mode" == power-saving ]] || fail "invalid AMDGPU power profile"
+		grep -Eq '^[[:space:]]*2[[:space:]]+POWER_SAVING' "$dev/pp_power_profile_mode" ||
+			fail "AMDGPU device ${dev##*/} does not expose POWER_SAVING as profile 2"
+		printf 'manual\n' >"$dev/power_dpm_force_performance_level"
+		printf '2\n' >"$dev/pp_power_profile_mode"
 	done
 
 	((found)) || fail "no supported AMDGPU device was found"
